
upstream project1_app {
    server 10.0.20.22:8001;
    # server 10.0.20.22:8001;
}

server {
    listen 80;
    server_name app.com www.app.com;

    location / {
        proxy_pass http://project1_app;

        # Symfony та Cloudflare things
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
